Repository gherlint/gherlint, pull requests merged in 2024-05, with the labels that each got.

#92 feat(rule): add new rule 'only_given_step_in_background'
  lib/config/gherlintrc.js
  lib/rules/index.js
  lib/rules/only_given_step_in_background.js
  tests/__fixtures__/Rules/only_given_step_in_background/fixture.js
  tests/lib/rules/only_given_step_in_background.test.js
Labels: feature, lint-rule

#99 feat(rule): add new rule 'lowercase_title'
  docs/adding_new_rule.md
  lib/config/gherlintrc.js
  lib/rules/index.js
  lib/rules/lowercase_title.js
  tests/__fixtures__/Rules/lowercase_title/fixture.js
  tests/lib/rules/lowercase_title.test.js
Labels: enhancement, feature

#101 feat: add -c,--config cli option
  lib/cli/CliOption.js
  lib/gherlint/GherlintConfig.js
  tests/lib/gherlint/GherlintConfig.test.js
Labels: feature
